---
razorpay:
 url: http://www.googles.com 
spring:
 application:
  name: boot
 banner:
  location: classpath:banner_print.txt
 main:
  banner-mode: console
 profiles:
  active: dev
vogo_id: 12345
bike_name: Vogo3go
cost: 50000
bike_num: TS1234
state: Telangana
autoconfiureenable: true
server:
 port: 8082
 servlet:
  context-path: /bike
info:
 author: satya
 version: 1.0
 released: 10-10-2021
 features: actuator
management:
 server:
  port: 8087
 endpoints:
  web:
   exposure:
    include:
    - "*"
   base-path: /management
   discovery:
    enabled: false
 endpoint:
  health:
   show-components: always
   show-details: always
   group: 
    satycare:
     include: 
     - db
     - diskSpace
...
---
spring:
 mvc:
  view:
   prefix: /WEB-INF/
   suffix: .jsp
 config:
  activate:
   on-profile: dev
 datasource:
  username: OIPASIT
  password: OIPASIT
  url: jdbc:oracle:thin:@localhost:1521:orcl
  driverclassname: oracle.jdbc.driver.OracleDriver
 jpa:
  show-sql: true
  generate-ddl: true
... 
---
spring:
 config:
  activate:
   on-profile: qa
 datasource:
  username: OIPASIT
  password: OIPASIT
  url: jdbc:oracle:thin:@localhost:1521:orcl
  driverclassname: oracle.jdbc.driver.OracleDriver
 jpa:
  show-sql: true
  generate-ddl: true 
...  
